obj-$(CONFIG_COMMON_CLK_MT6769_TOPCKGEN) += clk-mt6769-topckgen.o
obj-$(CONFIG_COMMON_CLK_MT6769_APMIXED) += clk-mt6769-apmixed.o
obj-$(CONFIG_COMMON_CLK_MT6769_INFRA) += clk-mt6769-infracfg.o
obj-$(CONFIG_COMMON_CLK_MT6779_MM) += clk-mt6779-mm.o
obj-$(CONFIG_COMMON_CLK_MT6779_MFG) += clk-mt6779-mfg.o
